### ISSUE TITLE
unresolved dependency: frege#fregec;3.22.524: not found

### ISSUE THREAD

**Issue by bgaster** [earldouglas/sbt-frege#18]
I added:

addSbtPlugin("com.earldouglas" % "sbt-frege" % "0.3.0")

to project/plugins.sbt

and

libraryDependencies += "frege" % "fregec" % "3.22.524" from
  "https://github.com/Frege/frege/releases/download/3.22.324/frege3.22.524-gcc99d7e.jar"

to build.sbt and then using sbt 0.13.7 (Scala 2.11.7) I get the following error:

info] Resolving frege#fregec;3.22.524 ...
[warn] 	module not found: frege#fregec;3.22.524
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/frege/fregec/3.22.524/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/frege/fregec/3.22.524/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/br-gaster/.ivy2/local/frege/fregec/3.22.524/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/frege/fregec/3.22.524/fregec-3.22.524.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: frege#fregec;3.22.524: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		frege:fregec:3.22.524
[warn] 		  +- com.earldouglas:sbt-frege:0.3.0 (scalaVersion=2.10, sbtVersion=0.13) (/Users/br-gaster/dev/whatsit2d/project/plugins.sbt#L1-2)
[warn] 		  +- default:whatsit2d-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)

**Comment by earldouglas** [comment]
This is now [fixed in sbt-frege 0.4.0](https://github.com/earldouglas/sbt-frege/pull/20).
