### ISSUE TITLE
Classes from dependent modules are not found when compiling Frege

### ISSUE THREAD

**Issue by LGLO** [earldouglas/sbt-frege#31]
In project with two subprojects:
```
lazy val plainJava = project
lazy val fregeCallsJava = project dependsOn plainJava
```
Error occurs when compiling `fregeCallsJava` because class from `plainJava` is not found.

Shoud I provide minimal project tgz with this issue?

**Comment by earldouglas** [comment]
Thanks for reporting this.  I think I know why this is failing, so no need to provide a tgz for now.

**Comment by earldouglas** [comment]
Ok, I found the issue.  We're currently only including `managedClasspath in Compile` in our call to `fregec`.  We need to also include `dependencyClasspath in Compile`.  I'll get this fixed tonight.

**Comment by earldouglas** [comment]
@LGLO Can you check the test project in [`java-from-frege`][1] and confirm that it looks like your use case?

[1]: https://github.com/earldouglas/sbt-frege/tree/issue-31/src/sbt-test/sbt-frege/java-from-frege

**Comment by LGLO** [comment]
Yes, it does.
Thank you very much!

**Comment by earldouglas** [comment]
Cool, give version 1.1.0 of sbt-frege a try, and let me know if you still run into this issue.

**Comment by LGLO** [comment]
1.1.0 has fixed my problem.
